version: '3'
services:
  # web:
  #   build: ./docker/php
  #   container_name: app
    # volumesはファイルがどこにあるか？
    # volumes:
    #   - ./:/var/www
    # ports:
    #   - 3000:3000
    # depends_on:
    #   - mysql

  app:
    # image: php:7.3-fpm
    build: ./docker/php
    volumes:
      - .:/var/www/mokumoku
      # - .:/var/www
    working_dir: /var/www/mokumoku
    depends_on:
      - mysql
  
  nginx:
    # image: nginx:1.15.6
    build: ./docker/nginx
    # container_name: app_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/mokumoku
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  
  mysql:
    image: mysql:8.0
    # container_name: app_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: development
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: yutaro
      MYSQL_PASSWORD: yutaro
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    depends_on:
      - mysql-volume

  mysql-volume:
    image: busybox
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

